In [3]:
import numpy as np
import time


In [12]:
#create - from Lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr),arr.shape)

arr2 = np.array([1,2,3,4,5,6,"ashu"])
print(arr2, type(arr2),arr2.shape) 

arr2D = np.array([[1,2,3,4,5],[2,3,4,5,5]])
print(arr2D,arr2D.shape)






[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' '6' 'ashu'] <class 'numpy.ndarray'> (7,)
[[1 2 3 4 5]
 [2 3 4 5 5]] (2, 5)
